id: I0AE3B203
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:50:06+00:00'
last_modified: '2022-06-08T02:58:49.776622+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23666
  title: བྱང་ཆུབ་ལམ་རིམ་གསེར་ཞུན་མ་དང་འཇམ་དཔལ་ཞལ་ལུང་། དེའི་ཁྲིད་རྒྱུན་ལྷོ་བརྒྱུད་དུ་གྲགས་པ་བཅས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B3C3:
      image_group_id: I1KG23735
      title: ''
      total_pages: 258
      order: 1
      base_file: B3C3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
