id: opecha:P005423
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23666
  title: བྱང་ཆུབ་ལམ་རིམ་གསེར་ཞུན་མ་དང་འཇམ་དཔལ་ཞལ་ལུང་། དེའི་ཁྲིད་རྒྱུན་ལྷོ་བརྒྱུད་དུ་གྲགས་པ་བཅས།
  volume: ''
  author: ''
