id: P005423
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23666
  title: བྱང་ཆུབ་ལམ་རིམ་གསེར་ཞུན་མ་དང་འཇམ་དཔལ་ཞལ་ལུང་། དེའི་ཁྲིད་རྒྱུན་ལྷོ་བརྒྱུད་དུ་གྲགས་པ་བཅས།
  author: ''
  volumes:
    273b83b60dbc4553a30a8fd090509103:
      image_group_id: I1KG23735
      title: ''
      volume_number: 1
      total_pages: 258
      base_file: v001.txt
